### ISSUE TITLE
Check for the right type when populating Profile object

### ISSUE THREAD

**Issue by costa974** [3pillarlabs/socialauth#36]
if (jObj.has("expires_in")) {
					String str = jObj.getString("expires_in");
					if (str != null && str.length() > 0) {
						expires = Integer.valueOf(str);
					}
				}

should be expires = jObj.getInt("expires_in");

dic 05, 2014 8:00:44 PM org.brickred.socialauth.SocialAuthManager connect
INFO: Connecting provider : googleplus
dic 05, 2014 8:00:44 PM org.brickred.socialauth.provider.GooglePlusImpl doVerifyResponse
INFO: Retrieving Access Token in verify response function
dic 05, 2014 8:00:44 PM org.brickred.socialauth.oauthstrategy.OAuth2 verifyResponse
INFO: Verifying the authentication response from provider
org.brickred.socialauth.exception.SocialAuthException: Unexpected auth response from https://accounts.google.com/o/oauth2/token
	at org.brickred.socialauth.oauthstrategy.OAuth2.verifyResponse(OAuth2.java:229)
	at org.brickred.socialauth.provider.GooglePlusImpl.doVerifyResponse(GooglePlusImpl.java:186)
	at org.brickred.socialauth.provider.GooglePlusImpl.verifyResponse(GooglePlusImpl.java:176)
	at org.brickred.socialauth.SocialAuthManager.connect(SocialAuthManager.java:184)
	at com.intellipeg.servlet.OAuthCallbackServlet.doGet(OAuthCallbackServlet.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by tarun-nagpal** [comment]
Done.
It was the issue with latest json API. Made changes in API and compatible with new json API.
Please use socialauth-4.8
