### ISSUE TITLE
twitter upload image does not works

### ISSUE THREAD

**Issue by vickyagrl** [3pillarlabs/socialauth#91]
Getting error while upload image with status in twitter.

org.brickred.socialauth.exception.SocialAuthException: java.net.ConnectException: Connection timed out: connect
	at org.brickred.socialauth.util.HttpUtil.doHttpRequest(HttpUtil.java:337)
	at org.brickred.socialauth.util.OAuthConsumer.uploadImage(OAuthConsumer.java:634)
	at org.brickred.socialauth.oauthstrategy.OAuth1.uploadImage(OAuth1.java:203)
	at org.brickred.socialauth.provider.TwitterImpl.uploadImage(TwitterImpl.java:511)

**Comment by tokajac** [comment]
Hello,
works here, once manager object is properly initialized and connected on callback, pseudocode:
_provider.uploadImage( statusMsg, imageName, new java.io.FileInputStream( imagePathOnServer ) )_
Does _updateStatus()_ works?
Might check twitter app settings in back-office and/or local firewall permissions
Regards

**Comment by vickyagrl** [comment]
it does not support multiple file uploads. it can only upload 1 file with status message.
